services:
  backend:
    build:
      context: ./backend-go/
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
  
  frontend:
    build:
      context: ./frontend-nextjs/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  